### ISSUE TITLE
command `which_email` gives error

### ISSUE THREAD

**Issue by shadiakiki1986** [minerva22/ffa-jobs-emails#4]
I created a new job in the admin page, and saw it in web app when I do a `python manage.py runserver`,
but when I run your command `which_email`, I get the below error
```
SIC_NAMECHECK> python manage.py which_email bla
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/shadi/Development/jobsproj/emailffa/management/commands/which_email.py", line 30, in handle
    email = Email.objects.filter(pk="email_text")
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/query.py", line 782, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/query.py", line 800, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1261, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1221, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1115, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 962, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'email_text'
```
I fixed it with the following `handle` function
```
    def handle(self,*args, **options):

        for job_name in options['job']:
            try:
                job = Job.objects.get(job_text=job_name)
            except Job.DoesNotExist:
                raise CommandError('Job "%s" does not exist' % job_name)   



            self.stdout.write('%s:' % (job_name))
            emails = Email.objects.filter(job=job)
            for email in emails:
              print("- "+email.email_text)
```
Usage example:
```
SIC_NAMECHECK> python manage.py which_email bla hey yo
bla:
- shadi@akikieng.com
- minerva@ffa.com
CommandError: Job "hey" does not exist
```

**Comment by minerva22** [comment]
adjusted
